### PR TITLE
common: add DAX bug workaround

### PR DESCRIPTION
**Pull request by marcinslusarz**
Enabled by PMEM_PREALLOC_SPACE_CREATE (for new pools) and
PMEM_PREALLOC_SPACE_OPEN (for pools not created with
PMEM_PREALLOC_SPACE_CREATE) environment variables.

[Review on Reviewable](https://reviewable.io/reviews/tomaszkapela/nvml/2)

### CODE REVIEW

**Comment by andyrudoff** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[src/common/set.c, line 1063 [r1]](https://reviewable.io:443/reviews/tomaszkapela/nvml/2#-K4hMetaP0n4tTbiMZMO:-K4hMetaP0n4tTbiMZMP:-51603432) ([raw file](https://github.com/tomaszkapela/nvml/blob/75b8d820ab6f5b8f975727d51bd434d29f701cab/src/common/set.c#L1063)):_
Trying out a couple comments, published together (instead of sent individually like github does).

---

_[src/common/set.c, line 1153 [r1]](https://reviewable.io:443/reviews/tomaszkapela/nvml/2#-K4hN4oCNc13kJaszTyB:-K4hN4oCNc13kJaszTyC:1153424371) ([raw file](https://github.com/tomaszkapela/nvml/blob/75b8d820ab6f5b8f975727d51bd434d29f701cab/src/common/set.c#L1153)):_
My goodness, this tool is very heavy on the eye-candy javascript.  Everything I do makes little icons pop-up and jump around the screen!

---

_[src/common/set.c, line 1331 [r1]](https://reviewable.io:443/reviews/tomaszkapela/nvml/2#-K4hNHJW1WYGbquNv_IE:-K4hNHJW1WYGbquNv_IF:-872044052) ([raw file](https://github.com/tomaszkapela/nvml/blob/75b8d820ab6f5b8f975727d51bd434d29f701cab/src/common/set.c#L1331)):_
Here's a comment on a part of the code that didn't change.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tomaszkapela/nvml/2)_

**Comment by tomaszkapela** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[src/common/set.c, line 1153 [r1]](https://reviewable.io:443/reviews/tomaszkapela/nvml/2#-K4hN4oCNc13kJaszTyB:-K4hP-BswIMibv_0T4Q_:114902289) ([raw file](https://github.com/tomaszkapela/nvml/blob/75b8d820ab6f5b8f975727d51bd434d29f701cab/src/common/set.c#L1153)):_
You can turn off all animations in the settings section of your account. You can also turn off the butterfly when you click on it. It's like the old paperclip helper from ms office. I find it quite nostalgic ;)

One neat thing is you can request an answer to your comment.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tomaszkapela/nvml/2)_

**Comment by andyrudoff** [comment]
_[src/common/set.c, line 1153 [r1]](https://reviewable.io:443/reviews/tomaszkapela/nvml/2#-K4hN4oCNc13kJaszTyB:-K4hPvsMqJCQXaqBNUPE:-1589168291) ([raw file](https://github.com/tomaszkapela/nvml/blob/75b8d820ab6f5b8f975727d51bd434d29f701cab/src/common/set.c#L1153)):_
I like the butterfly :+1: 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tomaszkapela/nvml/2)_

**Comment by tomaszkapela** [comment]
One nice feature is that rebasing and squashing does not remove comment history.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tomaszkapela/nvml/2#-:-K4hUVxupy4QAIJGbI6Y:868653495)_

**Pull request closed without merging**
