### PR TITLE
fix memory issue

### PR DESCRIPTION
**Pull request by plebioda**
[Review on Reviewable](https://reviewable.io/reviews/tomaszkapela/nvml/1)

### CODE REVIEW

**Comment by tomaszkapela** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/libpmemobj/obj.c, line 1230 [r1]](https://reviewable.io:443/reviews/tomaszkapela/nvml/1#-K4gVUmb_3KfGYEuWi3Z:-K4gVUmb_3KfGYEuWi3_:-1468838728) ([raw file](https://github.com/tomaszkapela/nvml/blob/7e92f7a90c3753102d1d424e952e842a0850b90a/src/libpmemobj/obj.c#L1230)):_
did you try turning it off and on again?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tomaszkapela/nvml/1)_

**Comment by marcinslusarz** [comment]
_[src/libpmemobj/obj.c, line 1230 [r1]](https://reviewable.io:443/reviews/tomaszkapela/nvml/1#-K4gVdTBOqnHNSTZh10T:-K4gVdTBOqnHNSTZh10U:-785362734) ([raw file](https://github.com/tomaszkapela/nvml/blob/7e92f7a90c3753102d1d424e952e842a0850b90a/src/libpmemobj/obj.c#L1230)):_
Approved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tomaszkapela/nvml/1)_

**Comment by plebioda** [comment]
_[src/libpmemobj/obj.c, line 1230 [r1]](https://reviewable.io:443/reviews/tomaszkapela/nvml/1#-K4gVUmb_3KfGYEuWi3Z:-K4gWMsC2kScnkbvQzIZ:-607825302) ([raw file](https://github.com/tomaszkapela/nvml/blob/7e92f7a90c3753102d1d424e952e842a0850b90a/src/libpmemobj/obj.c#L1230)):_
yes i did

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tomaszkapela/nvml/1)_

**Comment by marcinslusarz** [comment]
_[src/libpmemobj/obj.c, line 1219 [r2]](https://reviewable.io:443/reviews/tomaszkapela/nvml/1#-K4gWkejdhrFTvYOw33g:-K4gWkejdhrFTvYOw33h:-316714925) ([raw file](https://github.com/tomaszkapela/nvml/blob/0820f475d97057e217b4c858b6ff1b6ea3a0015b/src/libpmemobj/obj.c#L1219)):_
This is awesome. More patches like this!

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tomaszkapela/nvml/1)_

**Comment by plebioda** [comment]
_[src/libpmemobj/obj.c, line 1219 [r2]](https://reviewable.io:443/reviews/tomaszkapela/nvml/1#-K4gWkejdhrFTvYOw33g:-K4gWtnnws0BTNVRH9ME:-505228255) ([raw file](https://github.com/tomaszkapela/nvml/blob/0820f475d97057e217b4c858b6ff1b6ea3a0015b/src/libpmemobj/obj.c#L1219)):_
i'll do my best !

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tomaszkapela/nvml/1)_

**Comment by plebioda** [comment]
_[src/libpmemobj/obj.c, line 1219 [r2]](https://reviewable.io:443/reviews/tomaszkapela/nvml/1#-K4gWkejdhrFTvYOw33g:-K4gX-FB_xUA2faO8c5L:-499146009) ([raw file](https://github.com/tomaszkapela/nvml/blob/0820f475d97057e217b4c858b6ff1b6ea3a0015b/src/libpmemobj/obj.c#L1219)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tomaszkapela/nvml/1)_

**Comment by marcinslusarz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tomaszkapela/nvml/1)_

**Comment by tomaszkapela** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tomaszkapela/nvml/1)_

**Pull request merged**
